
#' Extract metrics of modeled luminescence signals
#'
#' @description Extracts metrics from OSL and TL curves generated by [RLumModel::model_LuminescenceSignals()]
#'
#' @param sequence [list] (**required**): set sequence to model as [list] or as *.seq file from the
#' Risø sequence editor.
#'
#' @param dose_rate [numeric] (**required**): laboratory dose rate in XXX
#' Gy/s for calculating seconds into Gray in the *.seq file.
#'
#' @param own_parameters [list] (**required**): This argument allows the user to submit own parameter sets. See details for more information.
#'
#' @param own_state_parameters [numeric] (**required**): Some publications (e.g., Pagonis 2009)
#' offer state parameters. With this argument the user can submit this state parameters. For further details
#' see vignette "RLumModel - Using own parameter sets" and example 3. The parameter also accepts an
#' [Luminescence::RLum.Results-class] object created by [.set_pars] as input.
#'
#' @return OSL and TL metrics
#' @export
#'
#' @examples see vignettes
Make_custom_model_and_retrieve_OSL_TL_metrics <- function(sequence, dose_rate, own_parameters, own_state_parameters) {


  sandbox_model <- model_LuminescenceSignals(
    model = "customized",
    sequence = sequence,
    lab.dose_rate = dose_rate,
    own_parameters = own_parameters,
    own_state_parameters = own_state_parameters,#,.set_pars("Bailey2001")$n,
    plot = FALSE,
    verbose = FALSE,
    simulate_sample_history = FALSE)


  OSL_metrics <- hash()
  TL_metrics <- hash()


  if ("OSL" %in% names(sequence)) {
    OSL_data <- get_RLum(sandbox_model, recordType ="OSL$", drop = FALSE)
    OSL_metrics <- Compute_OSL_metrics(sequence = sequence, data = OSL_data)
  }
  if ("TL" %in% names(sequence)) {
    TL_data <- get_RLum(sandbox_model, recordType ="TL$", drop = FALSE)
    TL_metrics <- Compute_TL_metrics(sequence = sequence, data = TL_data, automatic_peak_finder = TRUE)
  }

  return(list(OSL_metrics = OSL_metrics, TL_metrics = TL_metrics))

}
